server:
  runaddress: "0.0.0.0:80"

logger:
  level: "debug"
  path: "/app/logs/server.log"
  errorpath: "/app/logs/server_error.log"
  maxsize: 10
  maxbackups: 5
  maxage: 30
  compress: true

storage:
  type: "sqlite"
  db_path: "/app/data/loyality_system.db"
  migrations_path: "/app/migrations/sqlite"

admin:
  jwt_secret: "sirius-rating-system-secret-key-2025"
  static_dir: "/app/static/admin"
  admins_path: "/app/config/admins.json"

api:
  token: "sirius-rating-system-api-token-2025"
