server:
  address: ":80"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  shutdown_timeout: 20s

storage:
  type: "sqlite"
  dsn: "server/cmd/loyalityserver/data/loyality_system.db"

logger:
  level: "info"
  file: "server/cmd/loyalityserver/logs/server.log"
  error_file: "server/cmd/loyalityserver/logs/server_error.log"
