server:
  address: ":80"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  shutdown_timeout: 20s

storage:
  type: "sqlite"
  dsn: "/app/data/loyality_system.db"

logger:
  level: "info"
  path: "/app/logs/server.log"
  error_path: "/app/logs/server_error.log"
